version: "3"
services:
  backend:
    image: "thebookthief/watchlist_backend:latest"
    container_name: "backend"
    ports:
      - "8080:8080"

  frontend:
    image: "thebookthief/watchlist_frontend:latest"
    container_name: "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend